### ISSUE TITLE
How do i customize the escape menu further?

### ISSUE THREAD

**Issue by rxnfy** [codingcat2468/custom-escape-menu#2]
is it possible to further customize the remaining buttons in the escape menu or is mojang limiting us to just the banner and the back and title screen button?

**Comment by codingcat2468** [comment]
It it totally possible to do this, right now I'm on vacation for a few days, but I'll try making one when I get back!

**Comment by rxnfy** [comment]
any updates???!

**Comment by codingcat2468** [comment]
Really sorry for the delay, I have this working already, just waiting for @BugFinderMC to create some new example images now, then I'll release a version of the pack that supports this!

**Comment by Grievous07** [comment]
any update?

**Comment by codingcat2468** [comment]
Alright, I've finally created a version of the pack that supports every button in the menu, only took about **2 months**...
Seriously, sorry for the delay, I've been busy a lot lately and had kind of forgotten about this for a bit, but here it is!

You can find it in the [Releases](https://github.com/codingcat2468/custom-escape-menu/releases/tag/v1.0.0) section of this repository.
